---
abstract: 'The addition of simulating data to DBIx::Class'
author:
  - 'Rob Kinyon <rob.kinyon@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: DBIx::Class::Sims
name: DBIx-Class-Sims
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class::TopoSort: 0
  Data::Walk: 0
  List::Util: 0
  Scalar::Util: 0
  String::Random: 0
  YAML::XS: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
